In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz

In [2]:
iris = load_iris()


In [3]:
X = iris.data[:, 2:]
y = iris.target
tree_clf = DecisionTreeClassifier(max_depth=2)
tree_clf.fit(X, y)

DecisionTreeClassifier(max_depth=2)

In [4]:
PROJECT_ROOT_DIR = "."
CHAPTER_ID = "decision_trees"

def image_path(fig_id):
    return os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID, fig_id)

In [5]:
export_graphviz(
    tree_clf,
    out_file = image_path("iris_tree.dot"),
    feature_names=iris.feature_names[2:],
    class_names=iris.target_names,
    rounded=True,
    filled=True
)

In [6]:
tree_clf.predict_proba([[5,1.5]])

array([[0.        , 0.90740741, 0.09259259]])

In [7]:
tree_clf.predict_proba([[6,1.5]])

array([[0.        , 0.90740741, 0.09259259]])

In [8]:
from sklearn.tree import DecisionTreeRegressor
tree_reg = DecisionTreeRegressor(max_depth=2)
tree_reg.fit(X, y)

DecisionTreeRegressor(max_depth=2)

In [9]:
export_graphviz(
    tree_reg,
    out_file = image_path("iris_tree.dot"),
    feature_names=iris.feature_names[2:],
    class_names=iris.target_names,
    rounded=True,
    filled=True
)

In [10]:
tree_reg.predict([[5,1.5]])

array([1.09259259])

EXERCISE 7

In [11]:
from sklearn.datasets import make_moons

In [75]:
moons = make_moons(n_samples=10000, noise=0.4, random_state=42)

In [76]:
type(moons)

tuple

In [84]:
list(range(1,100))

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [77]:
from sklearn.model_selection import train_test_split

In [78]:
X_train, X_test, y_train, y_test = train_test_split(moons[0],moons[1], test_size=0.2, random_state=42)


In [79]:
m = len(X_train)
np.round(np.log2(m))

13.0

In [85]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
grid_params = {"max_leaf_nodes": list(range(1,100))}
tree_clf = DecisionTreeClassifier()

grid_search = GridSearchCV(tree_clf, grid_params, cv=3)
grid_search.fit(X_train, y_train)



/usr/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:378: FitFailedWarning: 
3 fits failed out of a total of 297.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/lib/python3.10/site-packages/sklearn/tree/_classes.py", line 969, in fit
    super().fit(
  File "/usr/lib/python3.10/site-packages/sklearn/tree/_classes.py", line 350, in fit
    check_scalar(
  File "/usr/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1480, in check_scalar
    raise ValueError(
V

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_leaf_nodes': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
                                            12, 13, 14, 15, 16, 17, 18, 19, 20,
                                            21, 22, 23, 24, 25, 26, 27, 28, 29,
                                            30, ...]})

In [87]:
grid_search.best_estimator_.fit(X_train, y_train)

DecisionTreeClassifier(max_leaf_nodes=17)

In [88]:
from sklearn.metrics import accuracy_score
y_pred = grid_search.best_estimator_.predict(X_test)

In [89]:
accuracy_score(y_test, y_pred)

0.8695

In [91]:
len(X_train)

8000

In [92]:
from sklearn.model_selection import ShuffleSplit

n_trees = 1000
n_instances = 100

mini_sets = []

rs = ShuffleSplit(n_splits=n_trees, test_size=len(X_train) - n_instances, random_state=42)
for mini_train_index, mini_test_index in rs.split(X_train):
    X_mini_train = X_train[mini_train_index]
    y_mini_train = y_train[mini_train_index]
    mini_sets.append((X_mini_train, y_mini_train))


In [120]:
mini_sets[n_trees-1]

(array([[ 1.729106  , -0.30293153],
        [ 0.82285486, -0.24639912],
        [ 0.6172433 ,  0.341603  ],
        [ 2.21942815, -0.52213898],
        [ 1.89842913, -0.45812873],
        [-0.91384812,  0.82723748],
        [ 0.12249021,  0.2451142 ],
        [ 0.52257396, -0.44650746],
        [-0.30268174,  1.2973055 ],
        [ 0.51989521,  0.26533397],
        [-0.71216241,  1.1853187 ],
        [ 2.40209241,  0.63410738],
        [ 0.75343015,  1.15911574],
        [ 1.0387203 , -0.62341768],
        [ 2.60009684,  0.32119377],
        [ 0.42509888,  0.13307243],
        [ 0.54796773,  0.95766374],
        [-0.79793684,  0.41911282],
        [ 1.56062298, -0.35677096],
        [ 1.25188949, -0.10284486],
        [ 1.89965546,  0.10692667],
        [ 0.600473  , -0.2956652 ],
        [-0.78906314,  0.62816483],
        [-0.26112405,  1.08783354],
        [ 1.10829435, -0.87313297],
        [ 0.74895939,  0.24851141],
        [ 0.2190207 , -0.01812386],
        [-0.43235994,  0.929

In [118]:
tree_clf = DecisionTreeClassifier(max_leaf_nodes=17)


In [121]:
for i in range(n_trees):
    tree_clf.fit(mini_sets[i][0], mini_sets[i][1])

In [122]:
y_pred = tree_clf.predict(X_test)
accuracy_score(y_test, y_pred)


0.834

ageron solution

In [125]:
from sklearn.base import clone
forest = [clone(grid_search.best_estimator_) for _ in range(n_trees)]


In [126]:
accuracy_scores = []
for tree, (X_mini_train, y_mini_train) in zip(forest, mini_sets):
    tree.fit(X_mini_train, y_mini_train)
    y_pred = tree.predict(X_test)
    accuracy_scores.append(accuracy_score(y_test, y_pred))

In [129]:
np.mean(accuracy_scores)

0.8054985

In [132]:
forest

[DecisionTreeClassifier(max_leaf_nodes=17),
 DecisionTreeClassifier(max_leaf_nodes=17),
 DecisionTreeClassifier(max_leaf_nodes=17),
 DecisionTreeClassifier(max_leaf_nodes=17),
 DecisionTreeClassifier(max_leaf_nodes=17),
 DecisionTreeClassifier(max_leaf_nodes=17),
 DecisionTreeClassifier(max_leaf_nodes=17),
 DecisionTreeClassifier(max_leaf_nodes=17),
 DecisionTreeClassifier(max_leaf_nodes=17),
 DecisionTreeClassifier(max_leaf_nodes=17),
 DecisionTreeClassifier(max_leaf_nodes=17),
 DecisionTreeClassifier(max_leaf_nodes=17),
 DecisionTreeClassifier(max_leaf_nodes=17),
 DecisionTreeClassifier(max_leaf_nodes=17),
 DecisionTreeClassifier(max_leaf_nodes=17),
 DecisionTreeClassifier(max_leaf_nodes=17),
 DecisionTreeClassifier(max_leaf_nodes=17),
 DecisionTreeClassifier(max_leaf_nodes=17),
 DecisionTreeClassifier(max_leaf_nodes=17),
 DecisionTreeClassifier(max_leaf_nodes=17),
 DecisionTreeClassifier(max_leaf_nodes=17),
 DecisionTreeClassifier(max_leaf_nodes=17),
 DecisionTreeClassifier(max_leaf

In [154]:
Y_pred = np.empty([n_trees, len(X_test)], dtype=np.uint8)

for tree_index, tree in enumerate(forest):
    Y_pred[tree_index] = tree.predict(X_test)


In [157]:
from scipy.stats import mode
y_pred_majority_votes, n_votes = mode(Y_pred, axis=0)

In [158]:
accuracy_score(y_test, y_pred_majority_votes.reshape([-1]))

0.8725

In [151]:
y_test.shape

(2000,)